### ISSUE TITLE
Check the reference implementation for recent developments

### ISSUE THREAD

**Issue by tdunning** [Cyral/t-digest-csharp#1]
The reference java implementation of t-digest has a number of improvements that substantially improve accuracy under some conditions. These include:

- two-level merging in the `MergingDigest`. This maintains better accuracy under almost all conditions with a minor speed and intermediate space hit.
- better interpolation, particularly in the tails. This can drive errors to zero in some cases or decrease tail errors significantly in other cases.
- guaranteed singleton clusters at the tails. This interacts with the previous change to drive tail accuracy
- stable sort. If you have lots of repeated values, especially near the tails, you could have invalid digests with the old sort.
- improved tests. This is always good, of course.

The README has lots of info. I would love to hear from you.

**Comment by Cyral** [comment]
Since I just wrote this implementation it should be all up to date. Thank you for the notification though.
